- id: build
  name: build
  description: Test Cargo build
  entry: cargo test
  language: system
  types: [rust]
  args: ["--no-run", "--locked"]
  
- id: test
  name: test
  description: Run Cargo tests
  entry: cargo test
  language: system
  types: [rust]
  args: ["--"]
  
- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
  
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
  
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
